server:
  port: '8082'

spring:
  profiles :
    active : Harshwardhan
---

spring:
  profiles : Harshwardhan
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/ems
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
